import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 Complex Sidebar Example:
 https://docusaurus.io/docs/sidebar#complex-sidebars-example
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Heroes',
      //link: {
      //  type: 'generated-index',
      //},
      collapsed: true,
      items: [
        'heroes/heroes-intro',
      ],
    },
    {
      type: 'category',
      label: 'Buildings',
      //link: {
      //  type: 'generated-index',
      //},
      collapsed: true,
      items: [
        'buildings/castle'
      ],
    },
    {
      type: 'category',
      label: 'Research',
      //link: {
      //  type: 'generated-index',
      //},
      collapsed: true,
      items: [
        'research/available-technologies',
      ],
    },
    {
      type: 'category',
      label: 'Events',
      //link: {
      //  type: 'generated-index',
      //},
      collapsed: true,
      items: [
        'events/guild-boss'
      ],
    },
    {
      type: 'category',
      label: 'Items & Resources',
      //link: {
      //  type: 'generated-index',
      //},
      collapsed: true,
      items: [
        'items-resources/resource-types'
      ],
    },
    {
      type: 'category',
      label: 'Gameplay',
      //link: {
      //  type: 'generated-index',
      //},
      collapsed: true,
      items: [
        'gameplay/adventure-mode'
      ],
    },
    {
      type: 'category',
      label: 'User Interface (UI)',
      //link: {
      //  type: 'generated-index',
      //},
      collapsed: true,
      items: [
        'ui/vip'
      ],
    },
  ],
};

export default sidebars;
