---
name: topheroes-gh-pages
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: 22
    
    - name: Install
      run: npm ci

    - name: Build
      run: |
        npm run build
        echo topheroes.wiki > build/CNAME

    - name: Save Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: 'topheroeswiki'
        path: build        

    - name: Deploy
      uses: actions/deploy-pages@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        ARTIFACT_NAME: 'topheroeswiki'
      